### ISSUE TITLE
gems with no rdoc still have the rdoc link

### ISSUE THREAD

**Issue by rdp** [quirkey/gembox#4]
ex: look at rdocs for sinatra via gembox:

Errno::ENOENT at /gems/doc/sinatra/0.9.2/index.html
No such file or directory - /home/rdp/installs/mbari_gembox_187/lib/ruby/gems/1.8/doc/sinatra-0.9.2/rdoc/index.html

Thanks!
-=r

**Comment by rdp** [comment]
syntax is a good example

**Comment by quirkey** [comment]
Rdoc only displays if there is an RDOC directory and the has_rdoc? gem spec option is checked. Closed by 44673f9223b62a404334ce361e3451bffc6414d0

Also, gems now reload if the mtime of your gems directory changes

**Comment by rdp** [comment]
Hmm.  The reload is great and awesome.  unfortunately it appears from recent changes to Gem [1] that has_rdoc is now "deprecated and ignored" [i.e. it generates rdocs for every gem now].  Keying off the existence of doc/index.html might be a surer way.
Thanks for your help with this!
=r
[1] http://rubygems.rubyforge.org/rdoc/Gem/Specification.html
