### ISSUE TITLE
gems don't seem to use the right entry page for rdoc

### ISSUE THREAD

**Issue by rdp** [quirkey/gembox#5]
if you install eventmachine, you'll notice its rdoc "first page" seems odd to me...I believe historically it's supposed to have defaulted to the EventMachine class, though doesn't seem to with gem server nor gembox. Hmm.

**Comment by quirkey** [comment]
I think this is actually an issue with the Eventmachine gem. You can specify these options for RDoc in your gem specification which the maintainers of EM have done incorrectly it seems.

**Comment by rdp** [comment]
I think so too.
=r
