### ISSUE TITLE
should the description be redclothed?

### ISSUE THREAD

**Issue by rdp** [quirkey/gembox#6]
for gems like hoe
http://gembox.faithpromotingrumors.org/gems/hoe/1.12.2
appears that the description is somewhat odd..thought?
-=r

**Comment by rdp** [comment]
putting it in a <pre></pre> seems to help
http://github.com/rogerdpack/gembox/commit/9947cb0ce7380a69f3ad6fd054b9443b25182a8a

**Comment by rdp** [comment]
.description
    =RDoc::Markup::ToHtml.new.convert(@gem.description) if @gem.description

helps sometimes

**Comment by quirkey** [comment]
Added RDoc formatting for gem description. Closed by 89247836db2adfeea72d780f87a500e9e20cb34f.
